---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/refs/tags/v2.10.0/schema/compose-spec.json
services:
  smoketest:
    build:
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
      context: ./vyos-build/docker
      dockerfile: Dockerfile
    networks:
      - test-amd64
    platform: linux/amd64
    privileged: true
    restart: "no"
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
    volumes:
      - ./vyos-build:/vyos:rw
    working_dir: /vyos
name: test-amd64
networks:
  test-amd64:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - gateway: 10.5.10.1
          subnet: 10.5.10.0/24
          ip_range: 10.5.10.128/25
    name: test-amd64
