---
jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.runner-os }}
    steps:
      - name: Define PLATFORM_PAIR
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Checkout repository vyos/vyos-build
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.vyos_build_ref }}
          repository: vyos/vyos-build
      - name: Log into registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - id: meta
        name: Extract metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/vyos-build
      - if: inputs.vyos_build_pr != ''
        name: Merge requested PRs from vyos/vyos-build
        run: |
          for pr in $(echo "${{ inputs.vyos_build_pr }}"); do
            title=$(gh pr view "$pr" --repo vyos/vyos-build --json title --template '{{.title}}')
            git config user.email "tbm-vyos@tech.bymatt.au"
            git config user.name "TBM VyOS"
            git fetch origin "pull/${pr}/head:pr-${pr}"
            git merge --no-commit "pr-${pr}"
          done
        working-directory: vyos-build
      - id: build
        name: Build and push by digest
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: docker
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/${{ github.repository_owner }}/vyos-build
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            runner-os: ubuntu-24.04
          - arch: arm64
            platform: linux/arm64
            runner-os: ubuntu-24.04-arm
    timeout-minutes: 30
  merge:
    name: Merge
    needs:
      - build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Download digests
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # 7.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Log into registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - id: meta
        name: Extract metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/vyos-build
          tags: type=raw,value=current
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/${{ github.repository_owner }}/vyos-build@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/vyos-build:current
    timeout-minutes: 10
name: Container
on:
  workflow_call:
    inputs:
      vyos_build_pr:
        description: List of vyos/vyos-build PR IDs to merge (optional)
        required: false
        type: string
      vyos_build_ref:
        default: current
        description: The vyos/vyos-build git ref to checkout
        required: false
        type: string
permissions:
  contents: read
