jobs:
 publish:
    name: Publish
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    uses: docker/github-builder/.github/workflows/build.yml@17bd7d64200cae4ba58ffc099934e8012ae320f2 # v1.10.0
    with:
      cache: true
      cache-mode: max
      context: vyos-build/docker
      labels: |
        org.opencontainers.image.source=https://github.com/vyos/vyos-build
      meta-images: ghcr.io/techbymatt/vyos-build
      meta-tags: |
        type=raw,value=rolling
      output: image 
      platforms: linux/amd64,linux/arm64
      push: true
name: Container
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
permissions:
  contents: read
