---
jobs:
  get:
    name: Get info
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - id: install_deps
        name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install --yes \
            lshw \
            qemu-efi-aarch64 \
            qemu-system-arm \
            util-linux
      - id: cat_proc_cpuinfo
        name: Print contents of /proc/cpuinfo
        run: |
          cat /proc/cpuinfo
      - id: lscpu
        name: Run lscpu
        run: |
          sudo lscpu
      - id: lshw
        name: Run lshw
        run: |
          sudo lshw
      - id: qemu_machines
        name: Query available QEMU machine types
        run: |
          qemu-system-aarch64 -machine help
      - id: qemu_cpus
        name: Query available QEMU CPU types
        run: |
          qemu-system-aarch64 -cpu help
name: System info
on:
  workflow_dispatch:
permissions:
  contents: read
