---
jobs:
  get:
    name: Get info
    runs-on: ${{ matrix.runner_label }}
    steps:
      - id: install_deps
        name: Install dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install --yes \
            cpu-checker \
            lshw \
            qemu-efi-aarch64 \
            qemu-system-arm \
            qemu-system-x86 \
            util-linux
      - id: cat_proc_cpuinfo
        name: Print contents of /proc/cpuinfo
        run: |
          cat /proc/cpuinfo
      - id: lscpu
        name: Run lscpu
        run: |
          sudo lscpu
      - id: lshw
        name: Run lshw
        run: |
          sudo lshw
      - id: kvm_ok
        name: Check KVM support
        run: |
          sudo kvm-ok
      - id: qemu_machines
        name: Query available QEMU machine types
        run: |
          qemu-system-aarch64 -machine help
      - id: qemu_cpus
        name: Query available QEMU CPU types
        run: |
          qemu-system-aarch64 -cpu help
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner_label: ubuntu-24.04
          - arch: arm64
            runner_label: ubuntu-24.04-arm
name: System info
on:
  workflow_dispatch:
permissions:
  contents: read
